// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-2)
// protocol is simulatable under MLWE(51,11,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(4,218,2^(45.633637))
// 
// Ring
// degree d = 128
// modulus q = 5846006549323611672814739330865132078623730172181, log(q) ~ 162.0
// factors q = q1
// 
// Compression
// D = 25
// gamma = 7198432708, log(gamma) ~ 32.745036
// 
// Dimensions of secrets
// s1: m1 = 156
// m: l = 0
// s2: m2 = 62
// 
// Size of secrets
// l2(s1) <= alpha = 242100.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: no
// exact euclidean: yes (dimensions: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], bounds: [59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 59.571591, 69888.0, 69888.0, 69888.0, 69888.0, 69888.0, 69888.0, 69888.0, 69888.0, 69888.0, 69888.0, 69888.0, 69888.0])
// approximate infinity: yes (psi: 2583.3311, dimension: 88, bound: 6.9776179e+8)
// 
// Challenge space
// c uniform in [-omega,omega] = [-2,2], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 59
// 
// Standard deviations
// stdev1 = 208037478.4, log(stdev1/1.55) = 27.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 26004684.8, log(stdev3/1.55) = 24.0
// stdev4 = 53257594470.4, log(stdev4/1.55) = 35.0
// 
// Repetition rate
// M1 = 2.5106386
// M2 = 1.4087219
// M3 = 1.0147116
// M4 = 1.0293459
// total = 3.6941407
// 
// Security
// MSIS dimension: 4
// MSIS root hermite factor: 1.0043601
// MLWE dimension: 51
// MLWE root hermite factor: 1.0043312
// 
// Proof size
// ~ 159.125000000000 KiB
// 
// 50 bit moduli for degree 128: [1125899906840833, 1125899906826241, 1125899906824961, 1125899906822657, 1125899906820097, 1125899906817793, 1125899906814209]
// bit length of products: [49, 99, 149, 199, 249, 299, 349]
// inverses: [1, -77158710720, -186207669797431, -233054335428326, -221150561204816, 169191676658877, 524953889855679]

#include "lazer.h"
static const limb_t _param_q_limbs[] = {277UL, 0UL, 17179869184UL};
static const int_t _param_q = {{(limb_t *)_param_q_limbs, 3, 0}};
static const limb_t _param_qminus1_limbs[] = {276UL, 0UL, 17179869184UL};
static const int_t _param_qminus1 = {{(limb_t *)_param_qminus1_limbs, 3, 0}};
static const limb_t _param_m_limbs[] = {8068804576427545621UL, 7131741081278904397UL, 2UL};
static const int_t _param_m = {{(limb_t *)_param_m_limbs, 3, 0}};
static const limb_t _param_mby2_limbs[] = {13257774325068548618UL, 3565870540639452198UL, 1UL};
static const int_t _param_mby2 = {{(limb_t *)_param_mby2_limbs, 3, 0}};
static const limb_t _param_gamma_limbs[] = {7198432708UL, 0UL, 0UL};
static const int_t _param_gamma = {{(limb_t *)_param_gamma_limbs, 3, 0}};
static const limb_t _param_gammaby2_limbs[] = {3599216354UL, 0UL, 0UL};
static const int_t _param_gammaby2 = {{(limb_t *)_param_gammaby2_limbs, 3, 0}};
static const limb_t _param_pow2D_limbs[] = {33554432UL, 0UL, 0UL};
static const int_t _param_pow2D = {{(limb_t *)_param_pow2D_limbs, 3, 0}};
static const limb_t _param_pow2Dby2_limbs[] = {16777216UL, 0UL, 0UL};
static const int_t _param_pow2Dby2 = {{(limb_t *)_param_pow2Dby2_limbs, 3, 0}};
static const limb_t _param_Bsq_limbs[] = {9773925155883420866UL, 584UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_Bsq = {{(limb_t *)_param_Bsq_limbs, 6, 0}};
static const limb_t _param_scM1_limbs[] = {7418383915201049924UL, 9419619363286359484UL, 2UL};
static const int_t _param_scM1 = {{(limb_t *)_param_scM1_limbs, 3, 0}};
static const limb_t _param_scM2_limbs[] = {517200680834753522UL, 7539589060805978723UL, 1UL};
static const int_t _param_scM2 = {{(limb_t *)_param_scM2_limbs, 3, 0}};
static const limb_t _param_scM3_limbs[] = {3046557414421998910UL, 271381284539162692UL, 1UL};
static const int_t _param_scM3 = {{(limb_t *)_param_scM3_limbs, 3, 0}};
static const limb_t _param_scM4_limbs[] = {13793398453576145073UL, 541335746418072334UL, 1UL};
static const int_t _param_scM4 = {{(limb_t *)_param_scM4_limbs, 3, 0}};
static const limb_t _param_stdev1sq_limbs[] = {43279592419030467UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev1sq = {{(limb_t *)_param_stdev1sq_limbs, 6, 0}};
static const limb_t _param_stdev2sq_limbs[] = {40307261UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev2sq = {{(limb_t *)_param_stdev2sq_limbs, 6, 0}};
static const limb_t _param_stdev3sq_limbs[] = {676243631547351UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev3sq = {{(limb_t *)_param_stdev3sq_limbs, 6, 0}};
static const limb_t _param_stdev4sq_limbs[] = {14019525496019259228UL, 153UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev4sq = {{(limb_t *)_param_stdev4sq_limbs, 6, 0}};
static const limb_t _param_inv2_limbs[] = {138UL, 0UL, 8589934592UL};
static const int_t _param_inv2 = {{(limb_t *)_param_inv2_limbs, 3, 1}};
static const limb_t _param_inv4_limbs[] = {69UL, 0UL, 4294967296UL};
static const int_t _param_inv4 = {{(limb_t *)_param_inv4_limbs, 3, 1}};
static const unsigned int _param_n[78] = {2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2};
static const limb_t _param_Bz3sqr_limbs[] = {465619167080897371UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_Bz3sqr = {{(limb_t *)_param_Bz3sqr_limbs, 6, 0}};
static const limb_t _param_Bz4_limbs[] = {852121511526UL, 0UL, 0UL};
static const int_t _param_Bz4 = {{(limb_t *)_param_Bz4_limbs, 3, 0}};
static const limb_t _param_Pmodq_limbs[] = {11106543746495351093UL, 14413555038447676673UL, 1831784176UL};
static const int_t _param_Pmodq = {{(limb_t *)_param_Pmodq_limbs, 3, 0}};
static const limb_t _param_l2Bsq0_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq0 = {{(limb_t *)_param_l2Bsq0_limbs, 3, 0}};
static const limb_t _param_l2Bsq1_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq1 = {{(limb_t *)_param_l2Bsq1_limbs, 3, 0}};
static const limb_t _param_l2Bsq2_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq2 = {{(limb_t *)_param_l2Bsq2_limbs, 3, 0}};
static const limb_t _param_l2Bsq3_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq3 = {{(limb_t *)_param_l2Bsq3_limbs, 3, 0}};
static const limb_t _param_l2Bsq4_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq4 = {{(limb_t *)_param_l2Bsq4_limbs, 3, 0}};
static const limb_t _param_l2Bsq5_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq5 = {{(limb_t *)_param_l2Bsq5_limbs, 3, 0}};
static const limb_t _param_l2Bsq6_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq6 = {{(limb_t *)_param_l2Bsq6_limbs, 3, 0}};
static const limb_t _param_l2Bsq7_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq7 = {{(limb_t *)_param_l2Bsq7_limbs, 3, 0}};
static const limb_t _param_l2Bsq8_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq8 = {{(limb_t *)_param_l2Bsq8_limbs, 3, 0}};
static const limb_t _param_l2Bsq9_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq9 = {{(limb_t *)_param_l2Bsq9_limbs, 3, 0}};
static const limb_t _param_l2Bsq10_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq10 = {{(limb_t *)_param_l2Bsq10_limbs, 3, 0}};
static const limb_t _param_l2Bsq11_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq11 = {{(limb_t *)_param_l2Bsq11_limbs, 3, 0}};
static const limb_t _param_l2Bsq12_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq12 = {{(limb_t *)_param_l2Bsq12_limbs, 3, 0}};
static const limb_t _param_l2Bsq13_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq13 = {{(limb_t *)_param_l2Bsq13_limbs, 3, 0}};
static const limb_t _param_l2Bsq14_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq14 = {{(limb_t *)_param_l2Bsq14_limbs, 3, 0}};
static const limb_t _param_l2Bsq15_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq15 = {{(limb_t *)_param_l2Bsq15_limbs, 3, 0}};
static const limb_t _param_l2Bsq16_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq16 = {{(limb_t *)_param_l2Bsq16_limbs, 3, 0}};
static const limb_t _param_l2Bsq17_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq17 = {{(limb_t *)_param_l2Bsq17_limbs, 3, 0}};
static const limb_t _param_l2Bsq18_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq18 = {{(limb_t *)_param_l2Bsq18_limbs, 3, 0}};
static const limb_t _param_l2Bsq19_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq19 = {{(limb_t *)_param_l2Bsq19_limbs, 3, 0}};
static const limb_t _param_l2Bsq20_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq20 = {{(limb_t *)_param_l2Bsq20_limbs, 3, 0}};
static const limb_t _param_l2Bsq21_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq21 = {{(limb_t *)_param_l2Bsq21_limbs, 3, 0}};
static const limb_t _param_l2Bsq22_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq22 = {{(limb_t *)_param_l2Bsq22_limbs, 3, 0}};
static const limb_t _param_l2Bsq23_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq23 = {{(limb_t *)_param_l2Bsq23_limbs, 3, 0}};
static const limb_t _param_l2Bsq24_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq24 = {{(limb_t *)_param_l2Bsq24_limbs, 3, 0}};
static const limb_t _param_l2Bsq25_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq25 = {{(limb_t *)_param_l2Bsq25_limbs, 3, 0}};
static const limb_t _param_l2Bsq26_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq26 = {{(limb_t *)_param_l2Bsq26_limbs, 3, 0}};
static const limb_t _param_l2Bsq27_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq27 = {{(limb_t *)_param_l2Bsq27_limbs, 3, 0}};
static const limb_t _param_l2Bsq28_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq28 = {{(limb_t *)_param_l2Bsq28_limbs, 3, 0}};
static const limb_t _param_l2Bsq29_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq29 = {{(limb_t *)_param_l2Bsq29_limbs, 3, 0}};
static const limb_t _param_l2Bsq30_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq30 = {{(limb_t *)_param_l2Bsq30_limbs, 3, 0}};
static const limb_t _param_l2Bsq31_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq31 = {{(limb_t *)_param_l2Bsq31_limbs, 3, 0}};
static const limb_t _param_l2Bsq32_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq32 = {{(limb_t *)_param_l2Bsq32_limbs, 3, 0}};
static const limb_t _param_l2Bsq33_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq33 = {{(limb_t *)_param_l2Bsq33_limbs, 3, 0}};
static const limb_t _param_l2Bsq34_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq34 = {{(limb_t *)_param_l2Bsq34_limbs, 3, 0}};
static const limb_t _param_l2Bsq35_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq35 = {{(limb_t *)_param_l2Bsq35_limbs, 3, 0}};
static const limb_t _param_l2Bsq36_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq36 = {{(limb_t *)_param_l2Bsq36_limbs, 3, 0}};
static const limb_t _param_l2Bsq37_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq37 = {{(limb_t *)_param_l2Bsq37_limbs, 3, 0}};
static const limb_t _param_l2Bsq38_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq38 = {{(limb_t *)_param_l2Bsq38_limbs, 3, 0}};
static const limb_t _param_l2Bsq39_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq39 = {{(limb_t *)_param_l2Bsq39_limbs, 3, 0}};
static const limb_t _param_l2Bsq40_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq40 = {{(limb_t *)_param_l2Bsq40_limbs, 3, 0}};
static const limb_t _param_l2Bsq41_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq41 = {{(limb_t *)_param_l2Bsq41_limbs, 3, 0}};
static const limb_t _param_l2Bsq42_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq42 = {{(limb_t *)_param_l2Bsq42_limbs, 3, 0}};
static const limb_t _param_l2Bsq43_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq43 = {{(limb_t *)_param_l2Bsq43_limbs, 3, 0}};
static const limb_t _param_l2Bsq44_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq44 = {{(limb_t *)_param_l2Bsq44_limbs, 3, 0}};
static const limb_t _param_l2Bsq45_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq45 = {{(limb_t *)_param_l2Bsq45_limbs, 3, 0}};
static const limb_t _param_l2Bsq46_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq46 = {{(limb_t *)_param_l2Bsq46_limbs, 3, 0}};
static const limb_t _param_l2Bsq47_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq47 = {{(limb_t *)_param_l2Bsq47_limbs, 3, 0}};
static const limb_t _param_l2Bsq48_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq48 = {{(limb_t *)_param_l2Bsq48_limbs, 3, 0}};
static const limb_t _param_l2Bsq49_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq49 = {{(limb_t *)_param_l2Bsq49_limbs, 3, 0}};
static const limb_t _param_l2Bsq50_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq50 = {{(limb_t *)_param_l2Bsq50_limbs, 3, 0}};
static const limb_t _param_l2Bsq51_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq51 = {{(limb_t *)_param_l2Bsq51_limbs, 3, 0}};
static const limb_t _param_l2Bsq52_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq52 = {{(limb_t *)_param_l2Bsq52_limbs, 3, 0}};
static const limb_t _param_l2Bsq53_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq53 = {{(limb_t *)_param_l2Bsq53_limbs, 3, 0}};
static const limb_t _param_l2Bsq54_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq54 = {{(limb_t *)_param_l2Bsq54_limbs, 3, 0}};
static const limb_t _param_l2Bsq55_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq55 = {{(limb_t *)_param_l2Bsq55_limbs, 3, 0}};
static const limb_t _param_l2Bsq56_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq56 = {{(limb_t *)_param_l2Bsq56_limbs, 3, 0}};
static const limb_t _param_l2Bsq57_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq57 = {{(limb_t *)_param_l2Bsq57_limbs, 3, 0}};
static const limb_t _param_l2Bsq58_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq58 = {{(limb_t *)_param_l2Bsq58_limbs, 3, 0}};
static const limb_t _param_l2Bsq59_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq59 = {{(limb_t *)_param_l2Bsq59_limbs, 3, 0}};
static const limb_t _param_l2Bsq60_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq60 = {{(limb_t *)_param_l2Bsq60_limbs, 3, 0}};
static const limb_t _param_l2Bsq61_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq61 = {{(limb_t *)_param_l2Bsq61_limbs, 3, 0}};
static const limb_t _param_l2Bsq62_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq62 = {{(limb_t *)_param_l2Bsq62_limbs, 3, 0}};
static const limb_t _param_l2Bsq63_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq63 = {{(limb_t *)_param_l2Bsq63_limbs, 3, 0}};
static const limb_t _param_l2Bsq64_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq64 = {{(limb_t *)_param_l2Bsq64_limbs, 3, 0}};
static const limb_t _param_l2Bsq65_limbs[] = {3549UL, 0UL, 0UL};
static const int_t _param_l2Bsq65 = {{(limb_t *)_param_l2Bsq65_limbs, 3, 0}};
static const limb_t _param_l2Bsq66_limbs[] = {4884332544UL, 0UL, 0UL};
static const int_t _param_l2Bsq66 = {{(limb_t *)_param_l2Bsq66_limbs, 3, 0}};
static const limb_t _param_l2Bsq67_limbs[] = {4884332544UL, 0UL, 0UL};
static const int_t _param_l2Bsq67 = {{(limb_t *)_param_l2Bsq67_limbs, 3, 0}};
static const limb_t _param_l2Bsq68_limbs[] = {4884332544UL, 0UL, 0UL};
static const int_t _param_l2Bsq68 = {{(limb_t *)_param_l2Bsq68_limbs, 3, 0}};
static const limb_t _param_l2Bsq69_limbs[] = {4884332544UL, 0UL, 0UL};
static const int_t _param_l2Bsq69 = {{(limb_t *)_param_l2Bsq69_limbs, 3, 0}};
static const limb_t _param_l2Bsq70_limbs[] = {4884332544UL, 0UL, 0UL};
static const int_t _param_l2Bsq70 = {{(limb_t *)_param_l2Bsq70_limbs, 3, 0}};
static const limb_t _param_l2Bsq71_limbs[] = {4884332544UL, 0UL, 0UL};
static const int_t _param_l2Bsq71 = {{(limb_t *)_param_l2Bsq71_limbs, 3, 0}};
static const limb_t _param_l2Bsq72_limbs[] = {4884332544UL, 0UL, 0UL};
static const int_t _param_l2Bsq72 = {{(limb_t *)_param_l2Bsq72_limbs, 3, 0}};
static const limb_t _param_l2Bsq73_limbs[] = {4884332544UL, 0UL, 0UL};
static const int_t _param_l2Bsq73 = {{(limb_t *)_param_l2Bsq73_limbs, 3, 0}};
static const limb_t _param_l2Bsq74_limbs[] = {4884332544UL, 0UL, 0UL};
static const int_t _param_l2Bsq74 = {{(limb_t *)_param_l2Bsq74_limbs, 3, 0}};
static const limb_t _param_l2Bsq75_limbs[] = {4884332544UL, 0UL, 0UL};
static const int_t _param_l2Bsq75 = {{(limb_t *)_param_l2Bsq75_limbs, 3, 0}};
static const limb_t _param_l2Bsq76_limbs[] = {4884332544UL, 0UL, 0UL};
static const int_t _param_l2Bsq76 = {{(limb_t *)_param_l2Bsq76_limbs, 3, 0}};
static const limb_t _param_l2Bsq77_limbs[] = {4884332544UL, 0UL, 0UL};
static const int_t _param_l2Bsq77 = {{(limb_t *)_param_l2Bsq77_limbs, 3, 0}};
static const limb_t _param_Ppmodq_0_limbs[] = {13289118762644121939UL, 5384567917144703106UL, 3241582490UL};
static const int_t _param_Ppmodq_0 = {{(limb_t *)_param_Ppmodq_0_limbs, 3, 1}};
static const limb_t _param_Ppmodq_1_limbs[] = {2995269033779360142UL, 13257450329221825232UL, 1282296403UL};
static const int_t _param_Ppmodq_1 = {{(limb_t *)_param_Ppmodq_1_limbs, 3, 0}};
static const limb_t _param_Ppmodq_2_limbs[] = {3885289776918934671UL, 6778459347578277811UL, 3143419642UL};
static const int_t _param_Ppmodq_2 = {{(limb_t *)_param_Ppmodq_2_limbs, 3, 0}};
static const limb_t _param_Ppmodq_3_limbs[] = {14570718646745988143UL, 12095611357193169608UL, 3751702908UL};
static const int_t _param_Ppmodq_3 = {{(limb_t *)_param_Ppmodq_3_limbs, 3, 1}};
static const limb_t _param_Ppmodq_4_limbs[] = {12821892305711572307UL, 18429434587729094953UL, 119274315UL};
static const int_t _param_Ppmodq_4 = {{(limb_t *)_param_Ppmodq_4_limbs, 3, 0}};
static const limb_t _param_Ppmodq_5_limbs[] = {17279905338503999211UL, 11972840228657705018UL, 6647628907UL};
static const int_t _param_Ppmodq_5 = {{(limb_t *)_param_Ppmodq_5_limbs, 3, 1}};
static const limb_t _param_Ppmodq_6_limbs[] = {5708762199287042413UL, 17576480285574877089UL, 5816363856UL};
static const int_t _param_Ppmodq_6 = {{(limb_t *)_param_Ppmodq_6_limbs, 3, 0}};
static const int_srcptr _param_l2Bsq[] = {_param_l2Bsq0, _param_l2Bsq1, _param_l2Bsq2, _param_l2Bsq3, _param_l2Bsq4, _param_l2Bsq5, _param_l2Bsq6, _param_l2Bsq7, _param_l2Bsq8, _param_l2Bsq9, _param_l2Bsq10, _param_l2Bsq11, _param_l2Bsq12, _param_l2Bsq13, _param_l2Bsq14, _param_l2Bsq15, _param_l2Bsq16, _param_l2Bsq17, _param_l2Bsq18, _param_l2Bsq19, _param_l2Bsq20, _param_l2Bsq21, _param_l2Bsq22, _param_l2Bsq23, _param_l2Bsq24, _param_l2Bsq25, _param_l2Bsq26, _param_l2Bsq27, _param_l2Bsq28, _param_l2Bsq29, _param_l2Bsq30, _param_l2Bsq31, _param_l2Bsq32, _param_l2Bsq33, _param_l2Bsq34, _param_l2Bsq35, _param_l2Bsq36, _param_l2Bsq37, _param_l2Bsq38, _param_l2Bsq39, _param_l2Bsq40, _param_l2Bsq41, _param_l2Bsq42, _param_l2Bsq43, _param_l2Bsq44, _param_l2Bsq45, _param_l2Bsq46, _param_l2Bsq47, _param_l2Bsq48, _param_l2Bsq49, _param_l2Bsq50, _param_l2Bsq51, _param_l2Bsq52, _param_l2Bsq53, _param_l2Bsq54, _param_l2Bsq55, _param_l2Bsq56, _param_l2Bsq57, _param_l2Bsq58, _param_l2Bsq59, _param_l2Bsq60, _param_l2Bsq61, _param_l2Bsq62, _param_l2Bsq63, _param_l2Bsq64, _param_l2Bsq65, _param_l2Bsq66, _param_l2Bsq67, _param_l2Bsq68, _param_l2Bsq69, _param_l2Bsq70, _param_l2Bsq71, _param_l2Bsq72, _param_l2Bsq73, _param_l2Bsq74, _param_l2Bsq75, _param_l2Bsq76, _param_l2Bsq77};
static const int_srcptr _param_Ppmodq[] = {_param_Ppmodq_0, _param_Ppmodq_1, _param_Ppmodq_2, _param_Ppmodq_3, _param_Ppmodq_4, _param_Ppmodq_5, _param_Ppmodq_6};
static const polyring_t _param_ring = {{_param_q, 128, 163, 7, moduli_d128, 7, _param_Pmodq, _param_Ppmodq, _param_inv2}};
static const dcompress_params_t _param_dcomp = {{ _param_q, _param_qminus1, _param_m, _param_mby2, _param_gamma, _param_gammaby2, _param_pow2D, _param_pow2Dby2, 25, 1, 130 }};
static const abdlop_params_t _param_tbox = {{ _param_ring, _param_dcomp, 234, 62, 0, 7, 4, _param_Bsq, 1, 2, 3, 59, 1, 27, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_eval_ = {{ _param_ring, _param_dcomp, 234, 62, 5, 2, 4, _param_Bsq, 1, 2, 3, 59, 1, 27, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_many_ = {{ _param_ring, _param_dcomp, 234, 62, 6, 1, 4, _param_Bsq, 1, 2, 3, 59, 1, 27, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const lnp_quad_eval_params_t _param_quad_eval = {{ _param_quad_eval_, _param_quad_many_, 2}};
static const lnp_tbox_params_t _param = {{ _param_tbox, _param_quad_eval, 0, _param_n, 88, 78, 234, 2, 24, _param_scM3, _param_stdev3sq, 2, 35, _param_scM4, _param_stdev4sq, _param_Bz3sqr, _param_Bz4, &_param_l2Bsq[0], _param_inv4, 162944UL }};

static const unsigned int param_Es0[2] = {0, 1};
static const unsigned int param_Es1[2] = {2, 3};
static const unsigned int param_Es2[2] = {4, 5};
static const unsigned int param_Es3[2] = {6, 7};
static const unsigned int param_Es4[2] = {8, 9};
static const unsigned int param_Es5[2] = {10, 11};
static const unsigned int param_Es6[2] = {12, 13};
static const unsigned int param_Es7[2] = {14, 15};
static const unsigned int param_Es8[2] = {16, 17};
static const unsigned int param_Es9[2] = {18, 19};
static const unsigned int param_Es10[2] = {20, 21};
static const unsigned int param_Es11[2] = {22, 23};
static const unsigned int param_Es12[2] = {24, 25};
static const unsigned int param_Es13[2] = {26, 27};
static const unsigned int param_Es14[2] = {28, 29};
static const unsigned int param_Es15[2] = {30, 31};
static const unsigned int param_Es16[2] = {32, 33};
static const unsigned int param_Es17[2] = {34, 35};
static const unsigned int param_Es18[2] = {36, 37};
static const unsigned int param_Es19[2] = {38, 39};
static const unsigned int param_Es20[2] = {40, 41};
static const unsigned int param_Es21[2] = {42, 43};
static const unsigned int param_Es22[2] = {44, 45};
static const unsigned int param_Es23[2] = {46, 47};
static const unsigned int param_Es24[2] = {48, 49};
static const unsigned int param_Es25[2] = {50, 51};
static const unsigned int param_Es26[2] = {52, 53};
static const unsigned int param_Es27[2] = {54, 55};
static const unsigned int param_Es28[2] = {56, 57};
static const unsigned int param_Es29[2] = {58, 59};
static const unsigned int param_Es30[2] = {60, 61};
static const unsigned int param_Es31[2] = {62, 63};
static const unsigned int param_Es32[2] = {64, 65};
static const unsigned int param_Es33[2] = {66, 67};
static const unsigned int param_Es34[2] = {68, 69};
static const unsigned int param_Es35[2] = {70, 71};
static const unsigned int param_Es36[2] = {72, 73};
static const unsigned int param_Es37[2] = {74, 75};
static const unsigned int param_Es38[2] = {76, 77};
static const unsigned int param_Es39[2] = {78, 79};
static const unsigned int param_Es40[2] = {80, 81};
static const unsigned int param_Es41[2] = {82, 83};
static const unsigned int param_Es42[2] = {84, 85};
static const unsigned int param_Es43[2] = {86, 87};
static const unsigned int param_Es44[2] = {88, 89};
static const unsigned int param_Es45[2] = {90, 91};
static const unsigned int param_Es46[2] = {92, 93};
static const unsigned int param_Es47[2] = {94, 95};
static const unsigned int param_Es48[2] = {96, 97};
static const unsigned int param_Es49[2] = {98, 99};
static const unsigned int param_Es50[2] = {100, 101};
static const unsigned int param_Es51[2] = {102, 103};
static const unsigned int param_Es52[2] = {104, 105};
static const unsigned int param_Es53[2] = {106, 107};
static const unsigned int param_Es54[2] = {108, 109};
static const unsigned int param_Es55[2] = {110, 111};
static const unsigned int param_Es56[2] = {112, 113};
static const unsigned int param_Es57[2] = {114, 115};
static const unsigned int param_Es58[2] = {116, 117};
static const unsigned int param_Es59[2] = {118, 119};
static const unsigned int param_Es60[2] = {120, 121};
static const unsigned int param_Es61[2] = {122, 123};
static const unsigned int param_Es62[2] = {124, 125};
static const unsigned int param_Es63[2] = {126, 127};
static const unsigned int param_Es64[2] = {128, 129};
static const unsigned int param_Es65[2] = {130, 131};
static const unsigned int param_Es66[2] = {132, 133};
static const unsigned int param_Es67[2] = {134, 135};
static const unsigned int param_Es68[2] = {136, 137};
static const unsigned int param_Es69[2] = {138, 139};
static const unsigned int param_Es70[2] = {140, 141};
static const unsigned int param_Es71[2] = {142, 143};
static const unsigned int param_Es72[2] = {144, 145};
static const unsigned int param_Es73[2] = {146, 147};
static const unsigned int param_Es74[2] = {148, 149};
static const unsigned int param_Es75[2] = {150, 151};
static const unsigned int param_Es76[2] = {152, 153};
static const unsigned int param_Es77[2] = {154, 155};
static const unsigned int *param_Es[78] = { param_Es0, param_Es1, param_Es2, param_Es3, param_Es4, param_Es5, param_Es6, param_Es7, param_Es8, param_Es9, param_Es10, param_Es11, param_Es12, param_Es13, param_Es14, param_Es15, param_Es16, param_Es17, param_Es18, param_Es19, param_Es20, param_Es21, param_Es22, param_Es23, param_Es24, param_Es25, param_Es26, param_Es27, param_Es28, param_Es29, param_Es30, param_Es31, param_Es32, param_Es33, param_Es34, param_Es35, param_Es36, param_Es37, param_Es38, param_Es39, param_Es40, param_Es41, param_Es42, param_Es43, param_Es44, param_Es45, param_Es46, param_Es47, param_Es48, param_Es49, param_Es50, param_Es51, param_Es52, param_Es53, param_Es54, param_Es55, param_Es56, param_Es57, param_Es58, param_Es59, param_Es60, param_Es61, param_Es62, param_Es63, param_Es64, param_Es65, param_Es66, param_Es67, param_Es68, param_Es69, param_Es70, param_Es71, param_Es72, param_Es73, param_Es74, param_Es75, param_Es76, param_Es77, };
static const unsigned int param_Es_nrows[78] = {2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2};

static const limb_t param_p_limbs[] = {5121UL, 34344524504746480UL};
static const int_t param_p = {{(limb_t *)param_p_limbs, 2, 0}};
static const limb_t param_pinv_limbs[] = {15903199492056750908UL, 13577600604968042310UL, 2086939881UL};
static const int_t param_pinv = {{(limb_t *)param_pinv_limbs, 3, 0}};
static const unsigned int param_s1_indices[78] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77};
static const lin_params_t param = {{ _param, 256, param_p, param_pinv, 2, param_s1_indices, 78, NULL, 0,  NULL, 0, param_Es, param_Es_nrows, NULL, NULL }};

