// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-2)
// protocol is simulatable under MLWE(49,11,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(4,80,2^(44.589306))
// 
// Ring
// degree d = 128
// modulus q = 182687704666362864775460604089535377456991568501, log(q) ~ 157.0
// factors q = q1
// 
// Compression
// D = 24
// gamma = 3962438340, log(gamma) ~ 31.883741
// 
// Dimensions of secrets
// s1: m1 = 20
// m: l = 0
// s2: m2 = 60
// 
// Size of secrets
// l2(s1) <= alpha = 31161.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: no
// exact euclidean: yes (dimensions: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], bounds: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 22033.92, 22033.92])
// approximate infinity: yes (psi: 3994.5285, dimension: 4, bound: 28203418.0)
// 
// Challenge space
// c uniform in [-omega,omega] = [-2,2], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 59
// 
// Standard deviations
// stdev1 = 26004684.8, log(stdev1/1.55) = 24.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 3250585.6, log(stdev3/1.55) = 21.0
// stdev4 = 3328599654.4, log(stdev4/1.55) = 31.0
// 
// Repetition rate
// M1 = 2.5803904
// M2 = 1.3932353
// M3 = 1.0156048
// M4 = 1.0121705
// total = 3.6956284
// 
// Security
// MSIS dimension: 4
// MSIS root hermite factor: 1.0042952
// MLWE dimension: 49
// MLWE root hermite factor: 1.0043649
// 
// Proof size
// ~ 57.3125000000000 KiB
// 
// 50 bit moduli for degree 128: [1125899906840833, 1125899906826241, 1125899906824961, 1125899906822657, 1125899906820097, 1125899906817793, 1125899906814209]
// bit length of products: [49, 99, 149, 199, 249, 299, 349]
// inverses: [1, -77158710720, -186207669797431, -233054335428326, -221150561204816, 169191676658877, 524953889855679]

#include "lazer.h"
static const limb_t _param_q_limbs[] = {629UL, 0UL, 536870912UL};
static const int_t _param_q = {{(limb_t *)_param_q_limbs, 3, 0}};
static const limb_t _param_qminus1_limbs[] = {628UL, 0UL, 536870912UL};
static const int_t _param_qminus1 = {{(limb_t *)_param_qminus1_limbs, 3, 0}};
static const limb_t _param_m_limbs[] = {17353219301047589293UL, 2499350012417617127UL, 0UL};
static const int_t _param_m = {{(limb_t *)_param_m_limbs, 3, 0}};
static const limb_t _param_mby2_limbs[] = {17899981687378570454UL, 1249675006208808563UL, 0UL};
static const int_t _param_mby2 = {{(limb_t *)_param_mby2_limbs, 3, 0}};
static const limb_t _param_gamma_limbs[] = {3962438340UL, 0UL, 0UL};
static const int_t _param_gamma = {{(limb_t *)_param_gamma_limbs, 3, 0}};
static const limb_t _param_gammaby2_limbs[] = {1981219170UL, 0UL, 0UL};
static const int_t _param_gammaby2 = {{(limb_t *)_param_gammaby2_limbs, 3, 0}};
static const limb_t _param_pow2D_limbs[] = {16777216UL, 0UL, 0UL};
static const int_t _param_pow2D = {{(limb_t *)_param_pow2D_limbs, 3, 0}};
static const limb_t _param_pow2Dby2_limbs[] = {8388608UL, 0UL, 0UL};
static const int_t _param_pow2Dby2 = {{(limb_t *)_param_pow2Dby2_limbs, 3, 0}};
static const limb_t _param_Bsq_limbs[] = {3369416562125550287UL, 170UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_Bsq = {{(limb_t *)_param_Bsq_limbs, 6, 0}};
static const limb_t _param_scM1_limbs[] = {8342083497886170791UL, 10706312287502356149UL, 2UL};
static const int_t _param_scM1 = {{(limb_t *)_param_scM1_limbs, 3, 0}};
static const limb_t _param_scM2_limbs[] = {10428711535681250631UL, 7253910594398331162UL, 1UL};
static const int_t _param_scM2 = {{(limb_t *)_param_scM2_limbs, 3, 0}};
static const limb_t _param_scM3_limbs[] = {1297772713366986133UL, 287857286661183656UL, 1UL};
static const int_t _param_scM3 = {{(limb_t *)_param_scM3_limbs, 3, 0}};
static const limb_t _param_scM4_limbs[] = {6776859886333437218UL, 224506792581057123UL, 1UL};
static const int_t _param_scM4 = {{(limb_t *)_param_scM4_limbs, 3, 0}};
static const limb_t _param_stdev1sq_limbs[] = {676243631547351UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev1sq = {{(limb_t *)_param_stdev1sq_limbs, 6, 0}};
static const limb_t _param_stdev2sq_limbs[] = {40307261UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev2sq = {{(limb_t *)_param_stdev2sq_limbs, 6, 0}};
static const limb_t _param_stdev3sq_limbs[] = {10566306742927UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev3sq = {{(limb_t *)_param_stdev3sq_limbs, 6, 0}};
static const limb_t _param_stdev4sq_limbs[] = {11079575659271799439UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev4sq = {{(limb_t *)_param_stdev4sq_limbs, 6, 0}};
static const limb_t _param_inv2_limbs[] = {314UL, 0UL, 268435456UL};
static const int_t _param_inv2 = {{(limb_t *)_param_inv2_limbs, 3, 1}};
static const limb_t _param_inv4_limbs[] = {157UL, 0UL, 134217728UL};
static const int_t _param_inv4 = {{(limb_t *)_param_inv4_limbs, 3, 1}};
static const unsigned int _param_n[10] = {2, 2, 2, 2, 2, 2, 2, 2, 2, 2};
static const limb_t _param_Bz3sqr_limbs[] = {7275299485639021UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_Bz3sqr = {{(limb_t *)_param_Bz3sqr_limbs, 6, 0}};
static const limb_t _param_Bz4_limbs[] = {53257594470UL, 0UL, 0UL};
static const int_t _param_Bz4 = {{(limb_t *)_param_Bz4_limbs, 3, 0}};
static const limb_t _param_Pmodq_limbs[] = {14066761021875207220UL, 14773370450969870274UL, 151755374UL};
static const int_t _param_Pmodq = {{(limb_t *)_param_Pmodq_limbs, 3, 0}};
static const limb_t _param_l2Bsq0_limbs[] = {1UL, 0UL, 0UL};
static const int_t _param_l2Bsq0 = {{(limb_t *)_param_l2Bsq0_limbs, 3, 0}};
static const limb_t _param_l2Bsq1_limbs[] = {1UL, 0UL, 0UL};
static const int_t _param_l2Bsq1 = {{(limb_t *)_param_l2Bsq1_limbs, 3, 0}};
static const limb_t _param_l2Bsq2_limbs[] = {1UL, 0UL, 0UL};
static const int_t _param_l2Bsq2 = {{(limb_t *)_param_l2Bsq2_limbs, 3, 0}};
static const limb_t _param_l2Bsq3_limbs[] = {1UL, 0UL, 0UL};
static const int_t _param_l2Bsq3 = {{(limb_t *)_param_l2Bsq3_limbs, 3, 0}};
static const limb_t _param_l2Bsq4_limbs[] = {1UL, 0UL, 0UL};
static const int_t _param_l2Bsq4 = {{(limb_t *)_param_l2Bsq4_limbs, 3, 0}};
static const limb_t _param_l2Bsq5_limbs[] = {1UL, 0UL, 0UL};
static const int_t _param_l2Bsq5 = {{(limb_t *)_param_l2Bsq5_limbs, 3, 0}};
static const limb_t _param_l2Bsq6_limbs[] = {1UL, 0UL, 0UL};
static const int_t _param_l2Bsq6 = {{(limb_t *)_param_l2Bsq6_limbs, 3, 0}};
static const limb_t _param_l2Bsq7_limbs[] = {1UL, 0UL, 0UL};
static const int_t _param_l2Bsq7 = {{(limb_t *)_param_l2Bsq7_limbs, 3, 0}};
static const limb_t _param_l2Bsq8_limbs[] = {485493631UL, 0UL, 0UL};
static const int_t _param_l2Bsq8 = {{(limb_t *)_param_l2Bsq8_limbs, 3, 0}};
static const limb_t _param_l2Bsq9_limbs[] = {485493631UL, 0UL, 0UL};
static const int_t _param_l2Bsq9 = {{(limb_t *)_param_l2Bsq9_limbs, 3, 0}};
static const limb_t _param_Ppmodq_0_limbs[] = {13146165181897991873UL, 5341343401746854572UL, 40684442UL};
static const int_t _param_Ppmodq_0 = {{(limb_t *)_param_Ppmodq_0_limbs, 3, 1}};
static const limb_t _param_Ppmodq_1_limbs[] = {17788141262490105527UL, 13295815059059968181UL, 188227155UL};
static const int_t _param_Ppmodq_1 = {{(limb_t *)_param_Ppmodq_1_limbs, 3, 0}};
static const limb_t _param_Ppmodq_2_limbs[] = {769740458581414397UL, 11630346293272058407UL, 98133253UL};
static const int_t _param_Ppmodq_2 = {{(limb_t *)_param_Ppmodq_2_limbs, 3, 1}};
static const limb_t _param_Ppmodq_3_limbs[] = {6335287456734111948UL, 12058440258896026247UL, 13933948UL};
static const int_t _param_Ppmodq_3 = {{(limb_t *)_param_Ppmodq_3_limbs, 3, 1}};
static const limb_t _param_Ppmodq_4_limbs[] = {13614666123821840449UL, 19009018358825197UL, 98946892UL};
static const int_t _param_Ppmodq_4 = {{(limb_t *)_param_Ppmodq_4_limbs, 3, 0}};
static const limb_t _param_Ppmodq_5_limbs[] = {2191539642478661891UL, 11937289058880501825UL, 225505387UL};
static const int_t _param_Ppmodq_5 = {{(limb_t *)_param_Ppmodq_5_limbs, 3, 1}};
static const limb_t _param_Ppmodq_6_limbs[] = {12061316073169080454UL, 835906249898488833UL, 109543599UL};
static const int_t _param_Ppmodq_6 = {{(limb_t *)_param_Ppmodq_6_limbs, 3, 1}};
static const int_srcptr _param_l2Bsq[] = {_param_l2Bsq0, _param_l2Bsq1, _param_l2Bsq2, _param_l2Bsq3, _param_l2Bsq4, _param_l2Bsq5, _param_l2Bsq6, _param_l2Bsq7, _param_l2Bsq8, _param_l2Bsq9};
static const int_srcptr _param_Ppmodq[] = {_param_Ppmodq_0, _param_Ppmodq_1, _param_Ppmodq_2, _param_Ppmodq_3, _param_Ppmodq_4, _param_Ppmodq_5, _param_Ppmodq_6};
static const polyring_t _param_ring = {{_param_q, 128, 158, 7, moduli_d128, 7, _param_Pmodq, _param_Ppmodq, _param_inv2}};
static const dcompress_params_t _param_dcomp = {{ _param_q, _param_qminus1, _param_m, _param_mby2, _param_gamma, _param_gammaby2, _param_pow2D, _param_pow2Dby2, 24, 1, 126 }};
static const abdlop_params_t _param_tbox = {{ _param_ring, _param_dcomp, 30, 60, 0, 7, 4, _param_Bsq, 1, 2, 3, 59, 1, 24, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_eval_ = {{ _param_ring, _param_dcomp, 30, 60, 5, 2, 4, _param_Bsq, 1, 2, 3, 59, 1, 24, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_many_ = {{ _param_ring, _param_dcomp, 30, 60, 6, 1, 4, _param_Bsq, 1, 2, 3, 59, 1, 24, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const lnp_quad_eval_params_t _param_quad_eval = {{ _param_quad_eval_, _param_quad_many_, 2}};
static const lnp_tbox_params_t _param = {{ _param_tbox, _param_quad_eval, 0, _param_n, 4, 10, 30, 2, 21, _param_scM3, _param_stdev3sq, 2, 31, _param_scM4, _param_stdev4sq, _param_Bz3sqr, _param_Bz4, &_param_l2Bsq[0], _param_inv4, 58688UL }};

static const unsigned int param_Es0[2] = {0, 1};
static const unsigned int param_Es1[2] = {2, 3};
static const unsigned int param_Es2[2] = {4, 5};
static const unsigned int param_Es3[2] = {6, 7};
static const unsigned int param_Es4[2] = {8, 9};
static const unsigned int param_Es5[2] = {10, 11};
static const unsigned int param_Es6[2] = {12, 13};
static const unsigned int param_Es7[2] = {14, 15};
static const unsigned int param_Es8[2] = {16, 17};
static const unsigned int param_Es9[2] = {18, 19};
static const unsigned int *param_Es[10] = { param_Es0, param_Es1, param_Es2, param_Es3, param_Es4, param_Es5, param_Es6, param_Es7, param_Es8, param_Es9, };
static const unsigned int param_Es_nrows[10] = {2, 2, 2, 2, 2, 2, 2, 2, 2, 2};

static const limb_t param_p_limbs[] = {5121UL, 34344524504746480UL};
static const int_t param_p = {{(limb_t *)param_p_limbs, 2, 0}};
static const limb_t param_pinv_limbs[] = {15973104548749446341UL, 14631767789422091965UL, 75574519UL};
static const int_t param_pinv = {{(limb_t *)param_pinv_limbs, 3, 1}};
static const unsigned int param_s1_indices[10] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const lin_params_t param = {{ _param, 256, param_p, param_pinv, 2, param_s1_indices, 10, NULL, 0,  NULL, 0, param_Es, param_Es_nrows, NULL, NULL }};

