// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-2)
// protocol is simulatable under MLWE(45,10,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(3,149,2^(37.225889))
// 
// Ring
// degree d = 128
// modulus q = 44601490397061246283071436545296723011968941, log(q) ~ 145.0
// factors q = q1
// 
// Compression
// D = 17
// gamma = 26908780, log(gamma) ~ 24.681574
// 
// Dimensions of secrets
// s1: m1 = 94
// m: l = 0
// s2: m2 = 55
// 
// Size of secrets
// l2(s1) <= alpha = 110.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 94)
// exact euclidean: no
// approximate infinity: yes (psi: 2285.7746, dimension: 46, bound: 6016.5)
// 
// Challenge space
// c uniform in [-omega,omega] = [-2,2], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 59
// 
// Standard deviations
// stdev1 = 101580.8, log(stdev1/1.55) = 16.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 12697.6, log(stdev3/1.55) = 13.0
// stdev4 = 406323.2, log(stdev4/1.55) = 18.0
// 
// Repetition rate
// M1 = 2.3547392
// M2 = 1.3552594
// M3 = 1.012654
// M4 = 1.037635
// total = 3.3532885
// 
// Security
// MSIS dimension: 3
// MSIS root hermite factor: 1.0043221
// MLWE dimension: 45
// MLWE root hermite factor: 1.0043905
// 
// Proof size
// ~ 68.0429687500000 KiB
// 
// 50 bit moduli for degree 128: [1125899906840833, 1125899906826241, 1125899906824961, 1125899906822657, 1125899906820097, 1125899906817793, 1125899906814209]
// bit length of products: [49, 99, 149, 199, 249, 299, 349]
// inverses: [1, -77158710720, -186207669797431, -233054335428326, -221150561204816, 169191676658877, 524953889855679]

#include "lazer.h"
static const limb_t _param_q_limbs[] = {8109UL, 0UL, 131072UL};
static const int_t _param_q = {{(limb_t *)_param_q_limbs, 3, 0}};
static const limb_t _param_qminus1_limbs[] = {8108UL, 0UL, 131072UL};
static const int_t _param_qminus1 = {{(limb_t *)_param_qminus1_limbs, 3, 0}};
static const limb_t _param_m_limbs[] = {5657389616650879601UL, 89853632874818492UL, 0UL};
static const int_t _param_m = {{(limb_t *)_param_m_limbs, 3, 0}};
static const limb_t _param_mby2_limbs[] = {2828694808325439800UL, 44926816437409246UL, 0UL};
static const int_t _param_mby2 = {{(limb_t *)_param_mby2_limbs, 3, 0}};
static const limb_t _param_gamma_limbs[] = {26908780UL, 0UL, 0UL};
static const int_t _param_gamma = {{(limb_t *)_param_gamma_limbs, 3, 0}};
static const limb_t _param_gammaby2_limbs[] = {13454390UL, 0UL, 0UL};
static const int_t _param_gammaby2 = {{(limb_t *)_param_gammaby2_limbs, 3, 0}};
static const limb_t _param_pow2D_limbs[] = {131072UL, 0UL, 0UL};
static const int_t _param_pow2D = {{(limb_t *)_param_pow2D_limbs, 3, 0}};
static const limb_t _param_pow2Dby2_limbs[] = {65536UL, 0UL, 0UL};
static const int_t _param_pow2Dby2 = {{(limb_t *)_param_pow2Dby2_limbs, 3, 0}};
static const limb_t _param_Bsq_limbs[] = {115718698883930231UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_Bsq = {{(limb_t *)_param_Bsq_limbs, 6, 0}};
static const limb_t _param_scM1_limbs[] = {2803721538917628956UL, 6543783052888722318UL, 2UL};
static const int_t _param_scM1 = {{(limb_t *)_param_scM1_limbs, 3, 0}};
static const limb_t _param_scM2_limbs[] = {856075782616760196UL, 6553379049528777060UL, 1UL};
static const int_t _param_scM2 = {{(limb_t *)_param_scM2_limbs, 3, 0}};
static const limb_t _param_scM3_limbs[] = {13146794670989295928UL, 233425108851327177UL, 1UL};
static const int_t _param_scM3 = {{(limb_t *)_param_scM3_limbs, 3, 0}};
static const limb_t _param_scM4_limbs[] = {14168241838816334755UL, 694242546615871598UL, 1UL};
static const int_t _param_scM4 = {{(limb_t *)_param_scM4_limbs, 3, 0}};
static const limb_t _param_stdev1sq_limbs[] = {10318658929UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev1sq = {{(limb_t *)_param_stdev1sq_limbs, 6, 0}};
static const limb_t _param_stdev2sq_limbs[] = {40307261UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev2sq = {{(limb_t *)_param_stdev2sq_limbs, 6, 0}};
static const limb_t _param_stdev3sq_limbs[] = {161229046UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev3sq = {{(limb_t *)_param_stdev3sq_limbs, 6, 0}};
static const limb_t _param_stdev4sq_limbs[] = {165098542858UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev4sq = {{(limb_t *)_param_stdev4sq_limbs, 6, 0}};
static const limb_t _param_inv2_limbs[] = {4054UL, 0UL, 65536UL};
static const int_t _param_inv2 = {{(limb_t *)_param_inv2_limbs, 3, 1}};
static const limb_t _param_inv4_limbs[] = {2027UL, 0UL, 32768UL};
static const int_t _param_inv4 = {{(limb_t *)_param_inv4_limbs, 3, 1}};
static const unsigned int _param_n[0] = {};
static const limb_t _param_Bz3sqr_limbs[] = {111012260217UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_Bz3sqr = {{(limb_t *)_param_Bz3sqr_limbs, 6, 0}};
static const limb_t _param_Bz4_limbs[] = {6501171UL, 0UL, 0UL};
static const int_t _param_Bz4 = {{(limb_t *)_param_Bz4_limbs, 3, 0}};
static const limb_t _param_Pmodq_limbs[] = {5308363278133419368UL, 18404552470352942647UL, 59830UL};
static const int_t _param_Pmodq = {{(limb_t *)_param_Pmodq_limbs, 3, 0}};
static const limb_t _param_Ppmodq_0_limbs[] = {1898743218959124634UL, 15346601392630382731UL, 19228UL};
static const int_t _param_Ppmodq_0 = {{(limb_t *)_param_Ppmodq_0_limbs, 3, 1}};
static const limb_t _param_Ppmodq_1_limbs[] = {17331089407324923516UL, 1347114904391784907UL, 40643UL};
static const int_t _param_Ppmodq_1 = {{(limb_t *)_param_Ppmodq_1_limbs, 3, 0}};
static const limb_t _param_Ppmodq_2_limbs[] = {16008606605448370332UL, 9509931914502404294UL, 58519UL};
static const int_t _param_Ppmodq_2 = {{(limb_t *)_param_Ppmodq_2_limbs, 3, 1}};
static const limb_t _param_Ppmodq_3_limbs[] = {16886343025491357558UL, 14128410238004326900UL, 7440UL};
static const int_t _param_Ppmodq_3 = {{(limb_t *)_param_Ppmodq_3_limbs, 3, 1}};
static const limb_t _param_Ppmodq_4_limbs[] = {2738442462417068465UL, 7640524032074130027UL, 20405UL};
static const int_t _param_Ppmodq_4 = {{(limb_t *)_param_Ppmodq_4_limbs, 3, 0}};
static const limb_t _param_Ppmodq_5_limbs[] = {18361720546061834176UL, 8506158403398124622UL, 28676UL};
static const int_t _param_Ppmodq_5 = {{(limb_t *)_param_Ppmodq_5_limbs, 3, 1}};
static const limb_t _param_Ppmodq_6_limbs[] = {6497123723508458716UL, 12473954580184721503UL, 65460UL};
static const int_t _param_Ppmodq_6 = {{(limb_t *)_param_Ppmodq_6_limbs, 3, 0}};
static const int_srcptr _param_l2Bsq[] = {};
static const int_srcptr _param_Ppmodq[] = {_param_Ppmodq_0, _param_Ppmodq_1, _param_Ppmodq_2, _param_Ppmodq_3, _param_Ppmodq_4, _param_Ppmodq_5, _param_Ppmodq_6};
static const polyring_t _param_ring = {{_param_q, 128, 146, 7, moduli_d128, 7, _param_Pmodq, _param_Ppmodq, _param_inv2}};
static const dcompress_params_t _param_dcomp = {{ _param_q, _param_qminus1, _param_m, _param_mby2, _param_gamma, _param_gammaby2, _param_pow2D, _param_pow2Dby2, 17, 1, 121 }};
static const abdlop_params_t _param_tbox = {{ _param_ring, _param_dcomp, 94, 55, 0, 7, 3, _param_Bsq, 1, 2, 3, 59, 1, 16, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_eval_ = {{ _param_ring, _param_dcomp, 94, 55, 5, 2, 3, _param_Bsq, 1, 2, 3, 59, 1, 16, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_many_ = {{ _param_ring, _param_dcomp, 94, 55, 6, 1, 3, _param_Bsq, 1, 2, 3, 59, 1, 16, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const lnp_quad_eval_params_t _param_quad_eval = {{ _param_quad_eval_, _param_quad_many_, 2}};
static const lnp_tbox_params_t _param = {{ _param_tbox, _param_quad_eval, 94, _param_n, 46, 0, 94, 2, 13, _param_scM3, _param_stdev3sq, 2, 18, _param_scM4, _param_stdev4sq, _param_Bz3sqr, _param_Bz4, &_param_l2Bsq[0], _param_inv4, 69676UL }};

static const unsigned int param_Ps[94] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93};

static const limb_t param_p_limbs[] = {5121UL, 34344524504746480UL};
static const int_t param_p = {{(limb_t *)param_p_limbs, 2, 0}};
static const limb_t param_pinv_limbs[] = {12229185891135603524UL, 4261813599759889233UL, 27827UL};
static const int_t param_pinv = {{(limb_t *)param_pinv_limbs, 3, 1}};
static const unsigned int param_s1_indices[47] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46};
static const lin_params_t param = {{ _param, 256, param_p, param_pinv, 2, param_s1_indices, 47, NULL, 0,  param_Ps, 94, NULL, NULL, NULL, NULL }};

