// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(51,11,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(4,156,2^(45.495602))
// 
// Ring
// degree d = 128
// modulus q = 5846006549323611672814739330865132078623730172181, log(q) ~ 162.0
// factors q = q1
// 
// Compression
// D = 25
// gamma = 7198432708, log(gamma) ~ 32.745036
// 
// Dimensions of secrets
// s1: m1 = 94
// m: l = 0
// s2: m2 = 62
// 
// Size of secrets
// l2(s1) <= alpha = 132204.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 50)
// exact euclidean: yes (dimensions: [44], bounds: [132203.52])
// approximate infinity: yes (psi: 2266.3992, dimension: 46, bound: 7.9533638e+8)
// 
// Challenge space
// c uniform in [-omega,omega] = [-2,2], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 59
// 
// Standard deviations
// stdev1 = 104018739.2, log(stdev1/1.55) = 26.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 13002342.4, log(stdev3/1.55) = 23.0
// stdev4 = 53257594470.4, log(stdev4/1.55) = 35.0
// 
// Repetition rate
// M1 = 2.733536
// M2 = 1.4087219
// M3 = 1.0175724
// M4 = 1.0382934
// total = 4.068511
// 
// Security
// MSIS dimension: 4
// MSIS root hermite factor: 1.0043337
// MLWE dimension: 51
// MLWE root hermite factor: 1.0043312
// 
// Proof size
// ~ 90.2812500000000 KiB
// 
// 50 bit moduli for degree 128: [1125899906840833, 1125899906826241, 1125899906824961, 1125899906822657, 1125899906820097, 1125899906817793, 1125899906814209]
// bit length of products: [49, 99, 149, 199, 249, 299, 349]
// inverses: [1, -77158710720, -186207669797431, -233054335428326, -221150561204816, 169191676658877, 524953889855679]

#include "lazer.h"
static const limb_t _param_q_limbs[] = {277UL, 0UL, 17179869184UL};
static const int_t _param_q = {{(limb_t *)_param_q_limbs, 3, 0}};
static const limb_t _param_qminus1_limbs[] = {276UL, 0UL, 17179869184UL};
static const int_t _param_qminus1 = {{(limb_t *)_param_qminus1_limbs, 3, 0}};
static const limb_t _param_m_limbs[] = {8068804576427545621UL, 7131741081278904397UL, 2UL};
static const int_t _param_m = {{(limb_t *)_param_m_limbs, 3, 0}};
static const limb_t _param_mby2_limbs[] = {13257774325068548618UL, 3565870540639452198UL, 1UL};
static const int_t _param_mby2 = {{(limb_t *)_param_mby2_limbs, 3, 0}};
static const limb_t _param_gamma_limbs[] = {7198432708UL, 0UL, 0UL};
static const int_t _param_gamma = {{(limb_t *)_param_gamma_limbs, 3, 0}};
static const limb_t _param_gammaby2_limbs[] = {3599216354UL, 0UL, 0UL};
static const int_t _param_gammaby2 = {{(limb_t *)_param_gammaby2_limbs, 3, 0}};
static const limb_t _param_pow2D_limbs[] = {33554432UL, 0UL, 0UL};
static const int_t _param_pow2D = {{(limb_t *)_param_pow2D_limbs, 3, 0}};
static const limb_t _param_pow2Dby2_limbs[] = {16777216UL, 0UL, 0UL};
static const int_t _param_pow2Dby2 = {{(limb_t *)_param_pow2Dby2_limbs, 3, 0}};
static const limb_t _param_Bsq_limbs[] = {9773925155883420866UL, 584UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_Bsq = {{(limb_t *)_param_Bsq_limbs, 6, 0}};
static const limb_t _param_scM1_limbs[] = {17182653893067404643UL, 13531350376339580231UL, 2UL};
static const int_t _param_scM1 = {{(limb_t *)_param_scM1_limbs, 3, 0}};
static const limb_t _param_scM2_limbs[] = {517200680834753522UL, 7539589060805978723UL, 1UL};
static const int_t _param_scM2 = {{(limb_t *)_param_scM2_limbs, 3, 0}};
static const limb_t _param_scM3_limbs[] = {12089275410145893824UL, 324153548895008119UL, 1UL};
static const int_t _param_scM3 = {{(limb_t *)_param_scM3_limbs, 3, 0}};
static const limb_t _param_scM4_limbs[] = {16107965288218762832UL, 706388842880145164UL, 1UL};
static const int_t _param_scM4 = {{(limb_t *)_param_scM4_limbs, 3, 0}};
static const limb_t _param_stdev1sq_limbs[] = {10819898104757617UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev1sq = {{(limb_t *)_param_stdev1sq_limbs, 6, 0}};
static const limb_t _param_stdev2sq_limbs[] = {40307261UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev2sq = {{(limb_t *)_param_stdev2sq_limbs, 6, 0}};
static const limb_t _param_stdev3sq_limbs[] = {169060907886838UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev3sq = {{(limb_t *)_param_stdev3sq_limbs, 6, 0}};
static const limb_t _param_stdev4sq_limbs[] = {14019525496019259228UL, 153UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev4sq = {{(limb_t *)_param_stdev4sq_limbs, 6, 0}};
static const limb_t _param_inv2_limbs[] = {138UL, 0UL, 8589934592UL};
static const int_t _param_inv2 = {{(limb_t *)_param_inv2_limbs, 3, 1}};
static const limb_t _param_inv4_limbs[] = {69UL, 0UL, 4294967296UL};
static const int_t _param_inv4 = {{(limb_t *)_param_inv4_limbs, 3, 1}};
static const unsigned int _param_n[1] = {44};
static const limb_t _param_Bz3sqr_limbs[] = {116404791770224342UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_Bz3sqr = {{(limb_t *)_param_Bz3sqr_limbs, 6, 0}};
static const limb_t _param_Bz4_limbs[] = {852121511526UL, 0UL, 0UL};
static const int_t _param_Bz4 = {{(limb_t *)_param_Bz4_limbs, 3, 0}};
static const limb_t _param_Pmodq_limbs[] = {11106543746495351093UL, 14413555038447676673UL, 1831784176UL};
static const int_t _param_Pmodq = {{(limb_t *)_param_Pmodq_limbs, 3, 0}};
static const limb_t _param_l2Bsq0_limbs[] = {17477770700UL, 0UL, 0UL};
static const int_t _param_l2Bsq0 = {{(limb_t *)_param_l2Bsq0_limbs, 3, 0}};
static const limb_t _param_Ppmodq_0_limbs[] = {13289118762644121939UL, 5384567917144703106UL, 3241582490UL};
static const int_t _param_Ppmodq_0 = {{(limb_t *)_param_Ppmodq_0_limbs, 3, 1}};
static const limb_t _param_Ppmodq_1_limbs[] = {2995269033779360142UL, 13257450329221825232UL, 1282296403UL};
static const int_t _param_Ppmodq_1 = {{(limb_t *)_param_Ppmodq_1_limbs, 3, 0}};
static const limb_t _param_Ppmodq_2_limbs[] = {3885289776918934671UL, 6778459347578277811UL, 3143419642UL};
static const int_t _param_Ppmodq_2 = {{(limb_t *)_param_Ppmodq_2_limbs, 3, 0}};
static const limb_t _param_Ppmodq_3_limbs[] = {14570718646745988143UL, 12095611357193169608UL, 3751702908UL};
static const int_t _param_Ppmodq_3 = {{(limb_t *)_param_Ppmodq_3_limbs, 3, 1}};
static const limb_t _param_Ppmodq_4_limbs[] = {12821892305711572307UL, 18429434587729094953UL, 119274315UL};
static const int_t _param_Ppmodq_4 = {{(limb_t *)_param_Ppmodq_4_limbs, 3, 0}};
static const limb_t _param_Ppmodq_5_limbs[] = {17279905338503999211UL, 11972840228657705018UL, 6647628907UL};
static const int_t _param_Ppmodq_5 = {{(limb_t *)_param_Ppmodq_5_limbs, 3, 1}};
static const limb_t _param_Ppmodq_6_limbs[] = {5708762199287042413UL, 17576480285574877089UL, 5816363856UL};
static const int_t _param_Ppmodq_6 = {{(limb_t *)_param_Ppmodq_6_limbs, 3, 0}};
static const int_srcptr _param_l2Bsq[] = {_param_l2Bsq0};
static const int_srcptr _param_Ppmodq[] = {_param_Ppmodq_0, _param_Ppmodq_1, _param_Ppmodq_2, _param_Ppmodq_3, _param_Ppmodq_4, _param_Ppmodq_5, _param_Ppmodq_6};
static const polyring_t _param_ring = {{_param_q, 128, 163, 7, moduli_d128, 7, _param_Pmodq, _param_Ppmodq, _param_inv2}};
static const dcompress_params_t _param_dcomp = {{ _param_q, _param_qminus1, _param_m, _param_mby2, _param_gamma, _param_gammaby2, _param_pow2D, _param_pow2Dby2, 25, 1, 130 }};
static const abdlop_params_t _param_tbox = {{ _param_ring, _param_dcomp, 95, 62, 0, 7, 4, _param_Bsq, 1, 2, 3, 59, 1, 26, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_eval_ = {{ _param_ring, _param_dcomp, 95, 62, 5, 2, 4, _param_Bsq, 1, 2, 3, 59, 1, 26, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_many_ = {{ _param_ring, _param_dcomp, 95, 62, 6, 1, 4, _param_Bsq, 1, 2, 3, 59, 1, 26, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const lnp_quad_eval_params_t _param_quad_eval = {{ _param_quad_eval_, _param_quad_many_, 2}};
static const lnp_tbox_params_t _param = {{ _param_tbox, _param_quad_eval, 50, _param_n, 46, 1, 95, 2, 23, _param_scM3, _param_stdev3sq, 2, 35, _param_scM4, _param_stdev4sq, _param_Bz3sqr, _param_Bz4, &_param_l2Bsq[0], _param_inv4, 92448UL }};

static const unsigned int param_Ps[50] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49};
static const unsigned int param_Es0[44] = {50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93};
static const unsigned int *param_Es[1] = { param_Es0, };
static const unsigned int param_Es_nrows[1] = {44};

static const limb_t param_p_limbs[] = {5121UL, 34344524504746480UL};
static const int_t param_p = {{(limb_t *)param_p_limbs, 2, 0}};
static const limb_t param_pinv_limbs[] = {15903199492056750908UL, 13577600604968042310UL, 2086939881UL};
static const int_t param_pinv = {{(limb_t *)param_pinv_limbs, 3, 0}};
static const unsigned int param_s1_indices[47] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46};
static const lin_params_t param = {{ _param, 256, param_p, param_pinv, 2, param_s1_indices, 47, NULL, 0,  param_Ps, 50, param_Es, param_Es_nrows, NULL, NULL }};

