// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(49,10,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(3,235,2^(38.734966))
// 
// Ring
// degree d = 128
// modulus q = 365375409332725729550921208179070754913983136381, log(q) ~ 158.0
// factors q = q1
// 
// Compression
// D = 18
// gamma = 53728660, log(gamma) ~ 25.679189
// 
// Dimensions of secrets
// s1: m1 = 176
// m: l = 0
// s2: m2 = 59
// 
// Size of secrets
// l2(s1) <= alpha = 5473.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: no
// exact euclidean: yes (dimensions: [176], bounds: [5472.0])
// approximate infinity: yes (psi: 3655.5988, dimension: 88, bound: 61636609.0)
// 
// Challenge space
// c uniform in [-omega,omega] = [-2,2], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 59
// 
// Standard deviations
// stdev1 = 3250585.6, log(stdev1/1.55) = 21.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 406323.2, log(stdev3/1.55) = 18.0
// stdev4 = 6657199308.8, log(stdev4/1.55) = 32.0
// 
// Repetition rate
// M1 = 3.7937924
// M2 = 1.3855559
// M3 = 1.0310316
// M4 = 1.014549
// total = 5.4984797
// 
// Security
// MSIS dimension: 3
// MSIS root hermite factor: 1.0042945
// MLWE dimension: 49
// MLWE root hermite factor: 1.0043992
// 
// Proof size
// ~ 111.589843750000 KiB
// 
// 50 bit moduli for degree 128: [1125899906840833, 1125899906826241, 1125899906824961, 1125899906822657, 1125899906820097, 1125899906817793, 1125899906814209]
// bit length of products: [49, 99, 149, 199, 249, 299, 349]
// inverses: [1, -77158710720, -186207669797431, -233054335428326, -221150561204816, 169191676658877, 524953889855679]

#include "lazer.h"
static const limb_t _param_q_limbs[] = {637UL, 0UL, 1073741824UL};
static const int_t _param_q = {{(limb_t *)_param_q_limbs, 3, 0}};
static const limb_t _param_qminus1_limbs[] = {636UL, 0UL, 1073741824UL};
static const int_t _param_qminus1 = {{(limb_t *)_param_qminus1_limbs, 3, 0}};
static const limb_t _param_m_limbs[] = {4686978283833233331UL, 18161306463670061478UL, 19UL};
static const int_t _param_m = {{(limb_t *)_param_m_limbs, 3, 0}};
static const limb_t _param_mby2_limbs[] = {2343489141916616665UL, 18304025268689806547UL, 9UL};
static const int_t _param_mby2 = {{(limb_t *)_param_mby2_limbs, 3, 0}};
static const limb_t _param_gamma_limbs[] = {53728660UL, 0UL, 0UL};
static const int_t _param_gamma = {{(limb_t *)_param_gamma_limbs, 3, 0}};
static const limb_t _param_gammaby2_limbs[] = {26864330UL, 0UL, 0UL};
static const int_t _param_gammaby2 = {{(limb_t *)_param_gammaby2_limbs, 3, 0}};
static const limb_t _param_pow2D_limbs[] = {262144UL, 0UL, 0UL};
static const int_t _param_pow2D = {{(limb_t *)_param_pow2D_limbs, 3, 0}};
static const limb_t _param_pow2Dby2_limbs[] = {131072UL, 0UL, 0UL};
static const int_t _param_pow2Dby2 = {{(limb_t *)_param_pow2Dby2_limbs, 3, 0}};
static const limb_t _param_Bsq_limbs[] = {460703675341367825UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_Bsq = {{(limb_t *)_param_Bsq_limbs, 6, 0}};
static const limb_t _param_scM1_limbs[] = {6699962081386701225UL, 14642885728954496559UL, 3UL};
static const int_t _param_scM1 = {{(limb_t *)_param_scM1_limbs, 3, 0}};
static const limb_t _param_scM2_limbs[] = {11279982919278562695UL, 7112251245900734075UL, 1UL};
static const int_t _param_scM2 = {{(limb_t *)_param_scM2_limbs, 3, 0}};
static const limb_t _param_scM3_limbs[] = {17749983226343834712UL, 572431204348615484UL, 1UL};
static const int_t _param_scM3 = {{(limb_t *)_param_scM3_limbs, 3, 0}};
static const limb_t _param_scM4_limbs[] = {2049947571042791637UL, 268382550633062488UL, 1UL};
static const int_t _param_scM4 = {{(limb_t *)_param_scM4_limbs, 3, 0}};
static const limb_t _param_stdev1sq_limbs[] = {10566306742927UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev1sq = {{(limb_t *)_param_stdev1sq_limbs, 6, 0}};
static const limb_t _param_stdev2sq_limbs[] = {40307261UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev2sq = {{(limb_t *)_param_stdev2sq_limbs, 6, 0}};
static const limb_t _param_stdev3sq_limbs[] = {165098542858UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev3sq = {{(limb_t *)_param_stdev3sq_limbs, 6, 0}};
static const limb_t _param_stdev4sq_limbs[] = {7424814489668094525UL, 2UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev4sq = {{(limb_t *)_param_stdev4sq_limbs, 6, 0}};
static const limb_t _param_inv2_limbs[] = {318UL, 0UL, 536870912UL};
static const int_t _param_inv2 = {{(limb_t *)_param_inv2_limbs, 3, 1}};
static const limb_t _param_inv4_limbs[] = {159UL, 0UL, 268435456UL};
static const int_t _param_inv4 = {{(limb_t *)_param_inv4_limbs, 3, 1}};
static const unsigned int _param_n[1] = {176};
static const limb_t _param_Bz3sqr_limbs[] = {113676554463109UL, 0UL, 0UL, 0UL, 0UL, 0UL};
static const int_t _param_Bz3sqr = {{(limb_t *)_param_Bz3sqr_limbs, 6, 0}};
static const limb_t _param_Bz4_limbs[] = {106515188940UL, 0UL, 0UL};
static const int_t _param_Bz4 = {{(limb_t *)_param_Bz4_limbs, 3, 0}};
static const limb_t _param_Pmodq_limbs[] = {6420249282029756709UL, 2585031487744314743UL, 154510672UL};
static const int_t _param_Pmodq = {{(limb_t *)_param_Pmodq_limbs, 3, 1}};
static const limb_t _param_l2Bsq0_limbs[] = {29942784UL, 0UL, 0UL};
static const int_t _param_l2Bsq0 = {{(limb_t *)_param_l2Bsq0_limbs, 3, 0}};
static const limb_t _param_Ppmodq_0_limbs[] = {12055213085886853832UL, 5362978522647213397UL, 30509978UL};
static const int_t _param_Ppmodq_0 = {{(limb_t *)_param_Ppmodq_0_limbs, 3, 1}};
static const limb_t _param_Ppmodq_1_limbs[] = {3991499735739918036UL, 13276612401477388546UL, 198401619UL};
static const int_t _param_Ppmodq_1 = {{(limb_t *)_param_Ppmodq_1_limbs, 3, 0}};
static const limb_t _param_Ppmodq_2_limbs[] = {5445455694678580374UL, 11649335576879391246UL, 87958789UL};
static const int_t _param_Ppmodq_2 = {{(limb_t *)_param_Ppmodq_2_limbs, 3, 1}};
static const limb_t _param_Ppmodq_3_limbs[] = {12670068555684674293UL, 6369698604361637985UL, 533111427UL};
static const int_t _param_Ppmodq_3 = {{(limb_t *)_param_Ppmodq_3_limbs, 3, 0}};
static const limb_t _param_Ppmodq_4_limbs[] = {14544843438844439585UL, 830555857434609UL, 109121356UL};
static const int_t _param_Ppmodq_4 = {{(limb_t *)_param_Ppmodq_4_limbs, 3, 0}};
static const limb_t _param_Ppmodq_5_limbs[] = {5826871630037071569UL, 11955083448226443638UL, 215330923UL};
static const int_t _param_Ppmodq_5 = {{(limb_t *)_param_Ppmodq_5_limbs, 3, 1}};
static const limb_t _param_Ppmodq_6_limbs[] = {11340732498382859600UL, 17593640881595822187UL, 437501776UL};
static const int_t _param_Ppmodq_6 = {{(limb_t *)_param_Ppmodq_6_limbs, 3, 0}};
static const int_srcptr _param_l2Bsq[] = {_param_l2Bsq0};
static const int_srcptr _param_Ppmodq[] = {_param_Ppmodq_0, _param_Ppmodq_1, _param_Ppmodq_2, _param_Ppmodq_3, _param_Ppmodq_4, _param_Ppmodq_5, _param_Ppmodq_6};
static const polyring_t _param_ring = {{_param_q, 128, 159, 7, moduli_d128, 7, _param_Pmodq, _param_Ppmodq, _param_inv2}};
static const dcompress_params_t _param_dcomp = {{ _param_q, _param_qminus1, _param_m, _param_mby2, _param_gamma, _param_gammaby2, _param_pow2D, _param_pow2Dby2, 18, 1, 133 }};
static const abdlop_params_t _param_tbox = {{ _param_ring, _param_dcomp, 177, 59, 0, 7, 3, _param_Bsq, 1, 2, 3, 59, 1, 21, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_eval_ = {{ _param_ring, _param_dcomp, 177, 59, 5, 2, 3, _param_Bsq, 1, 2, 3, 59, 1, 21, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_many_ = {{ _param_ring, _param_dcomp, 177, 59, 6, 1, 3, _param_Bsq, 1, 2, 3, 59, 1, 21, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const lnp_quad_eval_params_t _param_quad_eval = {{ _param_quad_eval_, _param_quad_many_, 2}};
static const lnp_tbox_params_t _param = {{ _param_tbox, _param_quad_eval, 0, _param_n, 88, 1, 177, 2, 18, _param_scM3, _param_stdev3sq, 2, 32, _param_scM4, _param_stdev4sq, _param_Bz3sqr, _param_Bz4, &_param_l2Bsq[0], _param_inv4, 114268UL }};

static const unsigned int param_Es0[176] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175};
static const unsigned int *param_Es[1] = { param_Es0, };
static const unsigned int param_Es_nrows[1] = {176};

static const limb_t param_p_limbs[] = {5121UL, 34344524504746480UL};
static const int_t param_p = {{(limb_t *)param_p_limbs, 2, 0}};
static const limb_t param_pinv_limbs[] = {6918780710778704580UL, 14161307647352779570UL, 335240930UL};
static const int_t param_pinv = {{(limb_t *)param_pinv_limbs, 3, 1}};
static const unsigned int param_s1_indices[88] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87};
static const lin_params_t param = {{ _param, 256, param_p, param_pinv, 2, param_s1_indices, 88, NULL, 0,  NULL, 0, param_Es, param_Es_nrows, NULL, NULL }};

